### ISSUE TITLE
Dungeon Enhanced Not Working

### ISSUE THREAD

**Issue by sgt502** [Mapaler/PADDashFormation#4]
I'm creating a team for Alt. Fourth Dimension Inspector. The dungeon boosts 6-star or lower rarity. 3x HP & 3x RCV. I had two cards with 6 or lower rarity but when I bring up Dungeon Enhanced menu, choose 5 & 6 star effective rarity, input 3x HP & 3x RCV, nothing happened. This is also occurs when I create a team for Christmas Dungeon.

**Comment by Mapaler** [comment]
I don't know why, I didn't get an email notification from github, and I'm just checking the issue now.
Regarding your question, you can provide your URL directly, so that I can quickly locate the problem.

**Comment by sgt502** [comment]
It was working fine a day or two after I submitted it. I thought it was you
who fixed it.
Next time if I experienced an issue, I will email you with the URL.

**Comment by Mapaler** [comment]
I have the impression that there is such a thing, I found this problem in my own use process, and then solved it.

I may have accidentally removed the github watch before, so didn't email me.
