### ISSUE TITLE
script-universal_function.js:1164 has a bug

### ISSUE THREAD

**Issue by hpp3** [Mapaler/PADDashFormation#7]
script-universal_function.js:1164: 
```

	const hp = ability ? ability[0] : 0;
>>>>    if (!hp) return 0;
	const mulHP = hp * memberHpMul(tMember, tAssist, ls2, memberArr, solo) //战友队长技
						 * memberHpMul(tMember, tAssist, ls1, memberArr, solo);//我方队长技
```
						 
This should not return 0 because countTeamHp should return an array. If it returns 0 then 

		let tHP = teamHPArr.reduce((pv, v) => pv + v); //队伍计算的总HP
		
will crash.

**Comment by Mapaler** [comment]
Thank you, fixed at d84ad0d5f356c3bd7610cc80ac00a493a9ba80ff
