### ISSUE TITLE
Super Awakenings unable to be selected on both Mobile and Desktop

### ISSUE THREAD

**Issue by taigercub** [Mapaler/PADDashFormation#9]
Super Awakenings for monsters can be clicked however the super awakening does not show on the monster and the effect is not applied to the team

**Comment by Mapaler** [comment]
> Super Awakenings for monsters can be clicked however the super awakening does not show on the monster and the effect is not applied to the team

Check if monster meet the conditions of level ≥100, +297?

Please paste your team link for me to reproduce the bug.

**Comment by taigercub** [comment]
All conditions seem to be met, here is the team link (https://mapaler.com/PADDashFormation/solo.html?d=%7B%22f%22%3A%5B%5B%5B%5B10996%2C99%2C9%2C99%2C%5B22%2C22%2C23%2C27%5D%5D%2C%5B5393%2C120%2C9%2C99%2C%5B48%2C11%2C11%5D%2C0%5D%2C%5B10959%2C120%2C9%2C99%2C%5B22%2C22%2C23%2C27%5D%2C0%5D%2C%5B10965%2C120%2C9%2C99%2C%5B15%2C11%2C11%5D%2C0%5D%2C%5B10301%2C99%2C9%2C99%2C%5B22%2C22%2C23%2C27%5D%2C0%5D%2C%5B10301%2C99%2C9%2C99%2C%5B22%2C22%2C23%2C27%5D%2C0%5D%5D%2C%5B%5B10233%2C99%2C6%2C99%5D%2C%5B10829%2C99%2C7%2C99%5D%2C%5B11261%2C99%2C7%2C99%5D%2C%5B9616%2C99%2C8%2C99%5D%2C%5B9993%2C99%2C5%2C99%5D%2C%5B9518%2C99%2C7%2C99%5D%5D%2C5%5D%5D%2C%22v%22%3A5%7D)

I seem to also be having another strange bug with editing latents, it seems as though when I try to edit latents it does not visually show the change until I leave the monster editing screen and go back into the team view, it also seems like when I edit any latents and then click on another monster it will instantly replace all of that monsters latents with the latents from the recently edited monster

**Comment by Mapaler** [comment]
Yesterday a new bug was introduced due to the fixing of some old bugs, and after your reply I have checked myself and fixed the newly introduced bug. Have you tried to force refresh the page and try again

**Comment by taigercub** [comment]
Yep that seemed to fix it, thanks for the quick responses and amazing program, keep up the good work
